apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-8y1r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-8y1r
    app.kubernetes.io/part-of: tkrw-pr712-0075-0071-app
  name: devfile-sample-8y1r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-8y1r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-8y1r
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-8y1r@sha256:0b10a8b11965762817896ab9c5edde3ff3ea4744a8fe562a90fb73b2e0642c66
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
